org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Fixes errors caused by Loom version differences
loom.ignoreDependencyLoomVersionValidation=true

# Mod properties
mod_version=1.4.3
maven_group=net.trafficlunar.optionsprofiles
archives_name=optionsprofiles
enabled_platforms=fabric,neoforge

# Minecraft properties
minecraft_version=1.21.9

# Dependencies
architectury_api_version = 18.0.3
fabric_loader_version=0.17.2
fabric_api_version=0.134.0+1.21.9
neoforge_version=21.9.0-beta