org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

java_version=25

# Mod properties
mod_id=optionsprofiles
mod_version=1.4.5
mod_name=Options Profiles
mod_description=Load and save your options from in-game.
mod_author=trafficlunar

license=GNU GPL 3.0
group=net.trafficlunar.optionsprofiles

# Minecraft properties
minecraft_version=26.1
minecraft_version_range=[26.1, 26.2)

# Dependencies
fabric_loader_version=0.18.4
fabric_api_version=0.144.3+26.1
neoforge_version=26.1.0.8-beta
neoforge_loader_version_range=[4,)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1